library romanian;

Map<String, dynamic> values = {

  'universal':{
    'inapoi': 'Înapoi',
  },

  
  'adauga_metoda_plata': {

    'introduceti_datele_cardului': 'Introduceti datele cardului',
    'card_holder_title': 'CARDHOLDER',
    'valid_thru_title': 'VALID THRU',
    'expiry_date': '08/2028',
    'card_holder_hint': 'Card Holder',
    'card_number_text': 'XXXX XXXX XXXX XXXX',
    'adresa_web': 'https://www.paypal.com',
    'cvv': '322',
    'card_number_title': 'Card Number',
    'card_number_hint': '1453 2436 1198 4452',
    'necompletat': 'Necompletat',
    'incorect': 'Incorect',
    'nume': 'Nume',
    'card_holder_name_hint': 'Popescu',
    'cvv_title': 'CVV',
    'card_cvv': '● ● ●',
    'expired_date': 'Expired Date',
    'expiry_date_hint': '08/29',
    'necompletata': 'Necompletată',
    'incorecta': 'Incorectă',
    'plata_adauga': 'PLATĂ / ADAUGĂ',

    },
  
  'apel_video_pacient': {

    'va_rugam_asteptati': 'Vă rugăm așteptați după doctor să intre!',

    },
  
  'confirmare': {

    'confirmare_titlu': 'Confirmare',
    'master_card': 'Master Card',
    'card_number': '● ● ● ●  ● ● ● ●  ● ● ● ● 4455',
    'tip_plata': 'Paypal',
    'user': 'radutimofte@gmail.com',
    'banca': 'Bank',
    'stripe': 'Stripe',
    'adauga_metoda_de_plata': 'ADAUGĂ METODĂ DE PLATĂ',

    },
  
  'confirmare_servicii': {

    'confirma_plata': 'Confirmă plata',
    'servicii_pediatrie':'Servicii Pediatrie',
    'primiti_recomandare_reteta':'Primiți o recomandare și rețetă medicală',
    'ron':'RON',
    'subtotal':'Subtotal',
    'total':'Total',
    'confirma_plata_buton':'CONFIRMĂ PLATA',
    
    },


/////////////////////////////////////////////////////////////////////////////////

  // old Adrian Murgu
  'overrides': {
    'searchTextFieldPlaceholderLabel': 'Căutați',
    'timerPickerHourLabels': {'ora': 'Ora', 'ore': 'ore'},
    'timerPickerMinuteLabels': 'Min',
    'timerPickerSecondLabels': 'Sec',
    'alertDialogLabel': 'Info',
    'datePickerHourSemanticsLabel': 'Ora',
    'datePickerMinuteSemanticsLabel': {'minut': '1 Minut', 'minute': 'Minute'},
    'timerPickerHourLabel': {'ora': 'Ora', 'ore': 'ore'},
    'timerPickerMinuteLabel': 'Min',
    'timerPickerSecondLabel': 'Sec',
    'cutButtonLabel': 'decupare',
    'copyButtonLabel': 'copiere',
    'pasteButtonLabel': 'lipire',
    'selectAllButtonLabel': 'Selectați tot',
    'todayLabel': 'Azi',
    'datePickerMediumDate': {
      'shortWeekdays': [
        'Lun',
        'Mart',
        'Mie',
        'Joi',
        'Vin',
        'Sâm',
        'Dum',
      ],
      'shortMonths': [
        'Ian',
        'Feb',
        'Mar',
        'Apr',
        'Mai',
        'Iun',
        'Iul',
        'Aug',
        'Sep',
        'Oct',
        'Noi',
        'Dec',
      ],
      'months': [
        'Ianuarie',
        'Februarie',
        'Martie',
        'Aprilie',
        'Mai',
        'Iunie',
        'Iulie',
        'August',
        'Septembrie',
        'Octombrie',
        'Noiembrie',
        'Decembrie',
      ]
    }
  },
  /*
  'universal': {
    'lss':'Listă servicii:',
    'v':'Valoare:',
    'p':'Plătit:',

    'cpi':'Copiii dumneavostră (numele complet), separați prin virgulă',
    'cc':' Cont nou',
    'tff':'Modificați Numărul de Telefon',
    'malll':'Modificați mail-ul',
    'ds':'Descriere',
    'ai':'Arii de interes',
    'dmd':'Detalii medic',
    'textCont':'Vă rugăm să completați toate câmpurile de\n mai jos, pentru a vă putea crea un cont.',
    'textlogare':'Pentru logare, vă rugăm să introduceți \nadresa de email și parola.',
    'languageTitle': 'Selectați limba',
    'eroareServer': 'Am întâmpinat o problemă. Vă rugăm încercați mai târziu.',
    'campInvalid': 'Câmp invalid',
    'mandatoryField': 'Câmp obligatoriu',
    'telefonInvalid': 'Telefonul nu este valid',
    'emailInvalid': 'Adresa de email nu este validă',
    'telefon': 'Telefon ',
    '1':'Scrisoare medicală',
    '2':'Rețetă medicală',
    '3':'Adeverintă medicală',
    'judet' : 'Județ',
    'stergecont' : 'Șterge contul',
    'cons':'Consultații',
    'mc':'Modificați parola ',
    'nmx' : 'Modificați numele',
    'localitate':'Localitate',
    'ml' : 'Modificați localitatea',
    'jd' : 'Modificați județul',
    'pn' : 'Modificați prenumele',
    'sal' : 'Salvează',
    'email': 'Email',
    'back': 'Înapoi',
    'continue': 'Continuă',
    'yes': 'Da',
    'no': 'Nu',

    'nume': 'Nume',
    'prenume': 'Prenume',
    'ddn': 'Data de naștere',
    'password': 'Parola',
    'passwordConfirm': 'Confirmați parola',
    'register': 'Nu ai cont? ',
    'login': 'Intră în cont',
    'send': 'Creare cont',
    'ok': 'Ok',
    'anulare': 'Anulare',
    'deschide_setari': 'Deschide setări',
    'passMismatch': 'Parolele nu se potrivesc',
    'invalidCredentials': 'Datele introduse nu sunt valide. Introduceți datele de conectare și reîncercați.',
    'forgotPass': 'Resetează parola',
    'changePass': 'Resetează parola',
    'newPassword': 'Noua parolă',
    'pinEmailAlert': 'Pe adresa de email menționată a fost trimis un cod de verificare, vă rugăm introduceți codul:',
    'validationCode': 'Cod validare',
    'validationCodeError': 'Codul introdus nu este valid',
    'errorRegister132': 'Există deja un cont cu acest email!',
    'ddn_peste_18ani': 'Trebuie să aveți cel puțin 18 ani împliniți',
    'minim_caractere': 'Parola trebuie să aibă minim 6 caractere',
    'loginDateGresite': 'Date de autentificare greșite',
    'reseteazaParolaDateGresite': 'Acest email nu există în baza de date',
    'reseteazaParolaValideazaPin': 'Validează',
    'pinInvalid': 'Codul introdus nu este valid',
    'mesajUserNeasociat':
        'Momentan nu sunteți asociat unui dosar de pacient al clinicii noastre. Pentru mai multe detalii vă rugăm să contactați recepția clinicii.',
    'appUnavailable': 'Aplicație indisponibilă',
    'inchide': 'Închide',
    'selectati_sediul': 'Selectați sediul',
    'toate_sediile': 'Toate',
    'pinVal':'Validare PIN',

  },
  */

  'noInternet': {'noInternet': 'Vă rugăm să verificați conexiunea la internet', 'refresh': 'Încercați din nou'},
  'askPhoneEmail': {
    'tel': 'Introduceți numărul de telefon:',
    'email': 'Introduceți adresa de email:',
    'cancel': 'Anulare'
  },
  'accepta_termenii': {
    'text1':'Apăsați "Acceptă & Continuă" pentru a vă da acordul în privința termenilor și condițiilor de confidențialitate.',
    'termeni' : 'Termeni si Conditii',
    'welcome': 'Bine ați venit!',
    'patient': 'PATIENT',
    'healthcare': 'HEALTHCARE',
    'msg': 'Apăsați "Acceptă & Continuă" pentru a vă da acordul în privința',
    'msg_terms': 'termenilor',
    'msg_and': 'și',
    'msg_conditions': 'condițiilor de confidențialitate',
    'accepta_termenii': 'Acceptă & Continuă'
  },
  'termeni_conditii': {'title': 'Termeni și condiții'},
  'politica_conf': {'title': 'Politica de Confidențialitate'},
  'plati': {
    'title': 'Plăți',
    'neplatite':'Neplătite',
    'toate':'Toate',
  },
  'home': {
    'hp':'Plăți',
    'h11': 'Momentan nu au fost gasite plati neefectuate în dosarul dumneavoastra electronic',
    'h22':'Momentan nu au fost gasite plati în dosarul dumneavoastra electronic',
    'alc':'Alegeți pacientul',
    'ds':'Detalii consultație',
    'rpg':'Reprogramare',
    'irt':'Intră in consultație',
    'vd':'Vezi detalii',
    'pg':'Pediatrie generală',
    'mkc':'Modificare cont',
    'modS':'Modificări Salvate',
    'confident':'iStoma este un soft de gestiune a clinicilor si cabinetelor stomatologice dezvoltat, intretinut si comercializat de IDAVA SOLUTIONS SRL, cu sediul în ELECTROMAGNETICA BUSINESS PARK, Sector 5, București, înmatriculată la Registrul Comerțului sub numărul J40/20674/17.10.2022, având CUI RO30410797.\nCE INFORMAȚII COLECTĂM?\nINFORMAȚIILE OFERITE VOLUNTAR ȘI CONȘTIENT\nîn momentul în care completați un formular de contact. Prelucrăm datele dumneavoastră cu caracter personal pentru a vă putea răspunde la întrebări sau pentru a putea presta serviciile pe care le solicitați sau comandați. Date personale înseamnă orice informație care poate fi legată de o persoană fizică identificată sau identificabilă. Datele personale includ toate tipurile de informații directe sau indirecte, cum ar fi numele complet, adresa de email sau numărul de telefon.\nÎn cazul în care comandați produse de la noi, avem nevoie de aceste informații să vă putem livra produsele comandate.\nAceste informații vor fi stocate în perioada garanției serviciilor sau ale produselor pentru a vă putea contacta în cazul în care este necesar, dar strict legat de produsele și serviciile comandate.\n\n În cazul serviciilor care se reînnoiesc automat, avem nevoie de datele dvs. pentru a emite facturile viitoare și a le trimite pe adresa dvs. în formă electronică sau fizică.\nÎn cazul în care solicitați mai multe informații despre noi printr-un formular sau telefonic, vom utiliza adresa dvs. de email pentru a vă trimite unul sau mai multe mail-uri prin care vă prezentăm serviciile noastre, dar numai în urma unei solicitări concrete și exprese. Adițional dacă specificați numărul de telefon, este posibil să vă sunăm pentru a solicita mai multe informații sau pentru a răspunde la întrebările trimise.\nINFORMAȚII COLECTATE ÎN MOD AUTOMAT\nAdițional site-ul nostru colectează informații despre paginile vizitate și interacțiunea cu conținutul site-ului. Aceste activități vor fi salvate în istoric și vor fi utilizate pentru a analiza erorile apărute și pentru a îmbunătăți site-ul. Aceste log-uri vor conține și adresa dvs. de IP, informații despre browser-ul utilizat cât și despre dispozitivul hardware utilizat (modelul, sistemul de operare, identificator unic al dispozitivului, informații despre rețeaua de pe care vă conectați). Site-ul va plasa și un cookie pe dispozitivul de pe care îl accesați, urmând să fie utilizat pentru identificarea indirectă. Aceste informații nu vor fi utilizate decât pentru operarea site-ului, măsurarea performanței site-ului, traficului și rezultatele campaniilor de marketing. Nu vom vinde sau transfera aceste informații terților, indiferent de raporturile în care suntem cu aceștia, și vom păstra o strictă confidențialitate a lor. Aceste informații nu vor fi utilizate pentru a vă contacta (email, sms sau telefonic), ci pentru a îmbunătăți site-ul nostru, pentru a vă oferi informații relevante, pentru a studia exact ce căutați și a răspunde la întrebări.\nSite-ul nostru utilizează următoarele servicii externe pentru a colecta informațiile:\nGoogle Analitics\nGoogle Adwords și tracking\nFacebook și Facebook pixel\nYoutube\nCum păstrăm datele dvs. cu caracter personal?\nTrebuie să știți că datele personale pe care le-am colectat de la dvs. pot fi accesate doar de echipa noastră și în cazuri excepționale, doar în urma unui demers legal, de instituțiile publice din România care aplică legea.\n\nPrelucrăm datele cu caracter personal aplicând măsurile tehnice și organizatorice adecvate pentru a le proteja împotriva oricărei prelucrări ilegale, distrugerii sau pierderii accidentale sau intenționate, a alterării, divulgării, transmiterii neautorizate sau accesului neautorizat, inclusiv când respectivele date pot fi transmise prin rețea.\nVă rugăm să ne contactați pe adresa de email contact@istoma.ro pentru:\norice neregulă în funcționarea site-ului\norice suspiciune privind insecuritatea aplicației\norice solicitare în legatură cu exercitarea oricărui drept ce vă revine în temeiul legii',
    'sd':'Caută medic sau specialitate',
    'welcome': 'Bine ați venit pe',
    'tap_to_pay': 'Tap to pay',
    'sus': 'Bine ați venit ',
    'contul_meu': 'Contul meu',
    'interventii': 'Istoric consultații',
    'programari': 'Programări',
    'contact': 'Contact',
    'programarileMele': 'Programări',
    'card': 'Plăți',
    'programariFamilie': 'Programări familie',
    'programareNoua': 'Programare nouă',
    'listaPreturi': 'Lista de prețuri',
    'echipaDoctori': 'Echipă medicală',
    'tratamenteleMele': 'Tratamente',
    'radiografii': 'Arhivă medicală',
    'prescriptiileMele': 'Prescripții',
    'sold': 'Sold curent',
    'logout': 'Log out',
    'schimbaLimba': 'Schimbă limba',
    'feedback': 'Feedback',
    'sedii': 'Sedii',
    'programari_viitoare': 'Programări viitoare',
    'programari_trecute': 'Programări trecute',
    'urmatoarea_programare': 'Următoarea programare este pe _DATA_, la Medicul _MEDIC_.',
    'confirma': 'Intră în consultație',
    'anuleaza': 'Reprogramează',
    'de_facut': 'De făcut',
    'realizate': 'Realizate',
    'h1':'Nu ai nici o programare',
    'h2':'Nu uita: "Mai bine să previi decât să tratezi!"',
    'nicio_programare': 'Nu aveți nicio o consultație anterioară;\n \nNu uitați: "Mai bine să previi decât să tratezi"',
    'nicio_consultatie': 'Nu aveți nici o consultație anterioară',
    'nicio_interventie': 'Nu aveți prevăzute tratamente;\nNu uitați "Mai bine să previi decât să tratezi!"',
    'anuleaza_programarea': 'Anulați programarea?',
    'confirma_programarea': 'Confirmați programarea?',
    'yes': 'Da',
    'no': 'Nu',
    'solicitaProgramare': 'Solicită programare',
    'veziIstoric': 'Vezi istoric',
    'istoricProgramari': 'Istoric programări',
    'oProgramare1': 'Următoarea dumneavoastră programare este pe ',
    'oProgramare2': 'de la',
    'oProgramare3': 'la ',
    'maiMulteProgramari': 'Aveți următoarele programări:',
    'maiMulteProgramariLa': 'la ',
    'areProgramare': 'are programare'
  },
  'chooseUser': {'pentru': 'pentru', 'mine': 'mine'},
  'contul_meu': {
    'titlu': 'Contul meu',
    'va_putem_contacta': 'Vă putem contacta la:',
    'ne_permiteti': 'Ne permiteți să trimitem:',
    'sms_reamintire': 'SMS de reamintire a programării',
    'sms_recall': 'SMS de recall/profilactic',
    'sms_aniversare': 'SMS de aniversare',
    'newsletter_sms': 'Newsletter SMS',
    'newsletter_email': 'Newsletter Email',
    'modificati': 'Modificați',
    'Nume Personal':'Nume Personal',
    'Prenume Personal':'Prenume ',
    'lipsa_telefon':
        'Fără telefonul dumneavoastră, în situația excepțională în care medicul dumneavoastră întâmpina o problema și nu poate onora programarea, noi nu vă vom mai putea anunța cu privire la situația intervenită.',
    'lipsa_email': 'Fără adresa dumneavoastră de email puteți rata ofertele noastre periodice.',
    'sigur_doriti': 'Sigur doriți acest lucru?',
    'da': 'Da',
    'nu': 'Nu',
    'lipsa_sms_reamintire':
        'În situația excepțională în care medicul dumneavoastră întâmpină o problema și nu poate onora programarea, noi nu vă vom mai putea anunța cu privire la situația intervenită.',
    'lipsa_sms_recall':
        'Vă trimitem SMS de recall atunci când starea dumneavoastră medicală sau păstrarea acesteia fac necesar acest lucru. Prin bifarea căsuței NU, noi nu vă vom mai putea contacta în acest scop.',
    'preferinte': 'Preferințe comunicare',
    'date_contact': 'Date contact',
    'save': 'Salvați',
    'cancel': 'Anulează',
    'schimba_limba': 'Schimbă limba',
    'schimba_parola': 'Schimbă parola',
    'email_deja_folosit': 'Acest email este deja folosit',
    'cod_de_bare': 'Cod de bare',
    'alege': 'Alege',
    'pacient': 'Pacient',
    'msgSigurDoritiStergerea': 'Sigur doriți ștergerea contului?',

  },
  'schimba_parola': {
    'current_pass': 'Parola actuală',
    'incorect_pass': 'Parolă incorectă',
  },
  'poza_profil': {
    'titlu': 'Poză de profil',
    'schimba_poza': 'Schimbă poza',
    'camera': 'Cameră',
    'galerie': 'Galerie',
    'always_finish_activities_msg':
        'Aplicația nu poate face poze dacă aveți setarea "Nu păstrați activitățile" activată. Puteți dezactiva această opțiune din meniul "Opțiuni dezvoltator"',
    'cere_permisiune_camera': 'Aplicația are nevoie de permisiunea dumneavoastră pentru a putea face poze.',
    'cere_permisiune_galerie': 'Aplicația are nevoie de permisiunea dumneavoastră pentru a putea accesa pozele.'
  },
  'programareNoua': {
    'aleDat':'Selectează dată',
    'pentruMine': 'Pentru mine',
    'alegetiData': 'Vă rugăm să alegeți o dată',
    'alegetiAltaData': 'Nu sunt intervale libere în data selectată. Vă rugăm să alegeți o alta dată.',
    'completatiObservatii': 'Vă rugăm să completați câmpul Observații',
    'progAdaugata': 'Solicitarea a fost trimisă',
    'progAdaugataReala': 'Programarea a fost adaugată',
    'categorie': 'Specialitate medicală',
    'medic': 'Medic',
    'data': 'Dată',
    'observatii': 'Observații',
    'scrn': 'Scrie-ne mai multe',
    'alegeti': 'Alegeți',
    'alegetiCategoria': 'Alege specialitatea medicală',
    'alegetiServiciul': 'Alege serviciul',    
    'alegeListaDeServicii': 'Alege lista de servicii',
    'alegeServiciul': 'Alege serviciul :',
    'alegetiMotiv': 'Vă rugăm să alegeți unul dintre motive',
    'alegetiMedicul': 'Alege medic',
    'alegetiOra': 'Vă rugăm să alegeți o oră',
    'faraIntervaleLibere': 'Nu sunt intervale libere',
    'faraIntervaleLibereLaMedic': 'Nu sunt intervale libere la medicul selectat',
    'urmatorulInterval': 'Primul interval disponibil este pe DATA incepand cu ora INTERVAL.',
    'intervaleDisponibile': 'Intervale disponibile',
    'ok': 'Ok',
    'trimite': 'Solicita Programare',
    'urmatorulpas': 'Următorul pas',
    'nuSuntServiciiAlocateSpecializarii':'Nu exista servicii alocate specializarii',
    'eroare': 'Eroare',
    'selectatiUnServiciu': 'Selectați un serviciu pentru a continua',
    'nuAtiSelectatUnMedic': 'Nu ați selectat un medic.',
    'nuAtiSelectatOCategorie': 'Nu ați selectat o categorie!',
    'alegetiListaServicii': 'Alegeti o lista de servicii!',
    'alegetiOData': 'Alegeți o dată',
    'selectatiIntervalMedic': 'Vă rugăm să selectați un interval orar si un medic înainte de a continua.',
    'rezumatProgramare': 'Rezumat programare',
    'rezumatProgramareMedic': 'Medic:',
    'rezumatProgramareCategorie': 'Categorie:',
    'rezumatProgramareServiciuSelectat': 'Serviciul Selectat:',
    'rezumatProgramareData': 'Programare pe data de:',
    'rezumatProgramareOra': 'la ora:',
    'rezumatProgramarePretul': 'Prețul:',
    
  },
  'programarileLui': {
    'viitoare': 'Viitoare',
    'trecute': 'Complete',
    'nicioProgViitoare': 'Nicio programare viitoare',
    'nicioProg': 'Nicio programare',
    'nicioSolicitare': 'Nicio solicitare',
    'anulata': 'Anulată',
    'solicitari': 'Solicitări',
    'nuSuntDocumente': 'Nu există documente',
    
  },
  'tratamenteleLui': {
    'realizate': 'Realizate',
    'deFacut': 'De făcut',
    'niciunTratamentDeFacut': 'Niciun tratament de făcut',
    'niciunTratamentRealizat': 'Niciun tratament realizat'
  },
  'prescriptii': {
    'iv':'Investigații și prețuri',
    'prs':'Prescripţii medicale',
    'niciuna': 'Nici o prescripție',
    'descarca': 'Descarcă',
    'momentanNuAuFostGasitePrescriptii': 'Momentan nu au fost găsite prescripții în dosarul dumneavoastră electronic',
  },
  'prices': {
    'appBarTitle': 'Lista de prețuri',
    'search': 'Căutați...',
    'cancel': 'Anulați',
    'category': 'Specializare',
    'code': 'Cod',
    'name': 'Denumire',
    'price': 'Preț',
    'all': 'Toate specializarile',
    'RON': 'Preț (lei)',

  },
  'sold': {
    'sold': 'Soldul dumneavoastră la acest moment este:',
    'iban': 'IBAN-ul la care puteți plăti este:',
    'soldCopied': 'Soldul a fost copiat în clipboard',
    'ibanCopied': 'IBAN-ul a fost copiat în clipboard',
    'detailsCopied': 'Detaliile au fost copiate în clipboard',
    'infoDetalii': 'Vă rugăm ca la detaliile plății să treceți:',
    'plataProforma': 'Plată proformă',
    'plataFactura': 'Plată factură',
    'plata': 'Plată',
    'veziDetalii': 'Vezi detalii',
  },
  'soldDetalii': {
    'title': 'Detalii sold',
    'data': 'Data',
    'doctor': 'Medic',
    'interventie': 'Intervenție',
    'pret': 'Preț',
    'achitat': 'Achitat',
    'deAchitat': 'De achitat',
    'dinti': 'Dinți',
    'total': 'Rest de plată',
    'subtotal': 'Subtotal',
  },
  'feedback': {
    'intrebare': 'Cum evaluați ultima vizită la noi?',
    'observatii': 'Observații',
    'buton': 'Trimite',
    'completatiObs': 'Vă rugăm să completați câmpul observații',
    'acordaRating': 'Vă rugăm să acordați un rating'
  },
  'sedii': {
    'as': 'Alege Sediul',
    'harta': 'Harta',
    'hint': 'Lăsați-ne un mesaj',
    'btn': 'Trimite',
    'trimite_empty': 'Vă rugăm să completați câmpul.',
    'trimite_success': 'Mesajul dumneavoastră a fost transmis.',
  },
  'radiografii': {
    'c1':'Clinică pediatrică',
    '1.1':'1. Aspecte Generale',
    '1.2':'Prezentele Termeni și Condiții („Termeni și Condiții”) guvernează raporturile dintre IDAVA SOLUTIONS S.R.L., societatea care dezvoltă și întreține platforma iDava.ro, cu sediul lucrativ în România, București, Sector 5, Electromagnetica Business Park („Societatea” sau „Noi”) și persoanele care utilizează („Utilizatorul”) pagina de internet www.iDava.ro („Site-ul” sau „iDava.ro”) și/sau serviciile oferite de Societate prin intermediul Site-ului („Serviciile”).\nAccesarea și utilizarea Site-ului, inclusiv a oricărei pagini sau secțiuni componente ale acestora, sau a oricărui Serviciu furnizat prin intermediul Site-ului se poate face numai în conformitate cu prezentele Termeni și Condiții, care includ Politica de Confidențialitate și Politica privind Cookie-urile.\n \n Pentru a asigura respectarea condițiilor de acces și utilizare a Serviciilor, Utilizatorii trebuie să verifice, la momentul fiecărei accesări a Site-ului, Termenii și Condițiile de utilizare. Trebuie știut că omiterea analizării Termenilor și Condițiilor, dar utilizarea de către dumneavoastră a platformei iDava.ro presupune acceptarea acestui set de Termeni și Condiții (inclusiv orice actualizare a acestora).\n \n Acceptarea acestor Termeni și Condiții presupune că dumneavoastră înțelegeți să respectați politica noastră, astfel că aveți obligația de a nu posta informații ce conținut un limbaj nepotrivit sau care au un conținut discriminatoriu.\n \n Dacă nu sunteți de acord cu prevederile din acest set de Termeni și Condiții (inclusiv orice actualizare a acestuia), vă rugăm să nu utilizați, sau după caz, să încetați utilizarea Site-ului sau a Serviciilor oferite de Noi, după caz.',
'2.1':'2. Serviciile iDava.ro',
    '2.2':'Platforma iDava.ro oferă servicii către:\n-Utilizatori\n-Vizitatori\n-Utilizatori Clienți ',
    '3.0':'2.1. Crearea contului de Client, parole și responsabilități',
    '3.1':'Utilizatorii Vizitatori pot folosi anumite facilități oferite de Platforma iDava.ro și fără a avea un cont de Utilizator.\nPentru a beneficia de toate Serviciile oferite de Platforma iDava.ro, Utilizatorii Vizitatori trebuie să solicite o ofertă pe platforma iDava.ro, completând formularul disponibil în interfața secțiunii respective.\nPentru a folosi Serviciile oferite de Platforma iDava.ro, este necesar ca datele furnizate să fie adevărate, exacte și complete. Prin bifarea căsuței: "Confirm că datele introduse mai sus sunt reale" Utlizatorul Vizitator confirmă, în mod liber și neechivoc, că datele sunt conforme cu realitatea.\nTrebuie să ştiţi că datele personale pe care le-am colectat de la dumneavoastră pot fi accesate doar de echipa noastră şi, în cazuri excepţionale, doar în urma unui demers legal, de instituţiile publice din România care aplică legea. Prin bifarea căsuței: "Accept să fiu contactat/ă" Utlizatorul Vizitator confirmă, în mod liber și neechivoc, că este de acord ca un membru al echipei să ia legătura cu el.',
'4.0':'3. Protecția Contului de Utilizator',
'4.1':'Accesul dumneavoastră la contul de Utilizator al Platformei iDava.ro este protejat de o parolă, motiv pentru care vă recomandăm ca parola să nu fie dezvăluită niciunei alte persoane. De asemenea, vă recomandăm să ieșiți din contul de Utilizator la sfârșitul fiecărei sesiuni de utilizare și, totodată, să închideți fereastra browserului în care ați lucrat la sfârșitul navigării dumneavoastră în platforma iDava.ro.\nAceste sfaturi sunt destinate să înlăture accesul persoanelor neautorizate la informațiile dumneavoastră personale sau la corespondența dumneavoastră, motiv pentru care sunteți răspunzători de păstrarea confidențialității asupra informaților și a parolei dumneavoastră. Veți fi răspunzători de utilizarea înregistrării dumneavoastră, indiferent dacă utilizarea se face cu sau fără voia dumneavoastră. Sunteți de acord să sesizați platforma iDava.ro în legătură cu orice utilizare neautorizată a datelor dumneavoastră de înregistrare în Platforma iDava.ro. Platforma nu va fi răspunzătoare pentru nicio pagubă morală sau materială provocată prin nerespectarea de către dumneavoastră a măsurilor de securitate a datelor utilizate pentru accesarea ei.',

    'nicio_radiografie': 'Nicio radiografie',
    'momentanFaraDocumente': 'Momentan nu au fost găsite documente în dosarul dumneavoastră electronic',

  },

  'radiografieDimensiuneReala': {

    'imagineNedisponibila': 'Imaginea nu este disponibilă.',
    'descarca': 'Descarcă',
    'salut': 'Salut',

  },

  'completareDateFacturare': {

    'titlu': 'Date necesare plății',
    'cnpParinte': 'CNP părinte',
    'cnpCopil': 'CNP copil',
    'validareCNP': 'Introduceți un CNP valid',
    'completatiToateCampurile': 'Completați toate câmpurile',
    'completatiCnpParinte': 'Completați CNP-ul părintelui!',
    'completatiCnpCopil': 'Completați CNP-ul copilului!',
    'completatiJudetul': 'Completați județul!',
    'completatiLocalitatea': 'Compila la località!',

  },

  'textPaginaNetopia': {
    'textCentrat': 'Ați fost redirecționat către pagina NETOPIA, pentru a finaliza PLATA serviciului selectat. Această plată este SECURIZATĂ, datele dumneavoastră fiind în SIGURANȚĂ.'
  },
  
  'voucher': {

    'title': 'Voucher',
    'nuAuFostGasiteVouchere': 'Momentan nu au fost gasite vouchere în dosarul dumneavoastra electronic',
    'nuUitaMaiBineSaTratezi': 'Nu uita: Mai bine să previi decât să tratezi!',
    'perioadaValabilitate':'Perioadă valabilitate ',
    'valoare': 'Valoare: ',

  },
  
  'alegeListaSpecializare': {
    'listaGoala': 'Listă goală',
  },

  'dosarulMeu': {
    'msgMomentanNuAuFostGasiteDocumente': 'Momentan nu au fost găsite consultații în dosarul dumneavoastră electronic',
  },

  'editJudet': {

    'alegeJudetul': 'Alegeți județul',
    'selecteazaJudetul': 'Selectează județul',
    'cautaJudetul': 'Căutați un județ...',

  },

  'editLocalitate': {

    'alegeLocalitatea': 'Alegeți localitatea',
    'selecteazaLocalitatea': 'Selectează localitate',
    'cautaLocalitatea': 'Căutați o localitate...',

  },

};
